export const Session = {
    FETCH_SESSION_USER: 'FETCH_SESSION_USER',
    REMOVE_SESSION_USER: 'REMOVE_SESSION_USER',
};

export const Error = {
    RECEIVE_ERROR: 'RECEIVE_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',
};
